global:
  scrape_interval: 20s
  scrape_timeout: 10s

scrape_configs:
  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Backend
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']

  # Backend Replica
  - job_name: 'backend-rep'
    static_configs:
      - targets: ['backend-rep:8001']
