global:
  scrape_interval: 20s #20초마다 targets metrics을 읽어옴
  scrape_timeout: 10s

rule_files:
  - "alert.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  # targets : metrics를 제공하고 있는 주소
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8081' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'backend'
    static_configs:
      - targets: [ 'backend:8000' ]

  - job_name: 'backend-rep'
    static_configs:
      - targets: [ 'backend-rep:8001' ]